#!/usr/bin/env bash
# LLLL installer for OpenAI Codex CLI
# Usage: ./install-codex.sh
#
# Creates or updates ~/.codex/AGENTS.md with LLLL integration.
# If AGENTS.md already exists, appends the LLLL section (idempotent).

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_MD="$HOME/.codex/AGENTS.md"

LLLL_SECTION=$(cat << EOF
# LLLL — Embedded Compliance Layer

You have **LLLL (Layrix Logic Layer Loop) v5.0** active as an embedded compliance engine.

---

## Passive Activation (Design-Time Mode)

After ANY output involving feature planning, PRD generation, architecture design, or code generation with compliance relevance, append:

\`\`\`
## ⚖️ Layrix Compliance Layer

Triggered domains:
- [domain — reason]

Potential issues:
- [gaps]

What is missing:
- [evidence or policy gaps]

What to do next:
| Action | Owner |
|--------|-------|

Preventive design suggestions:
- [specific change]

Education insight:
- Compliance: [concept]
- Business: [implication]

Next:
[1] Continue  [2] /llll deep  [3] /llll checklist  [4] /llll brief  [5] /llll diff
\`\`\`

---

## Command Invocation

When the user types any \`/llll\` command:

1. Read \`${INSTALL_DIR}/SKILL.md\` — your complete LLLL operating spec.
2. Read \`${INSTALL_DIR}/compliance-checklist-master.md\` — the compliance domain framework.
3. Execute the requested mode exactly as specified in SKILL.md.

Supported commands:

| Command | Mode |
|---------|------|
| \`/llll\` | Diagnosis |
| \`/llll deep\` | Deep Analysis |
| \`/llll checklist\` | Structured Intake |
| \`/llll brief\` | Expert Handoff Brief |
| \`/llll diff\` | Feature vs Policy Coverage |
| \`/llll scan\` | Automated Security Scan |
| \`/llll fix [ID]\` | Fix scan finding |
| \`/llll grc\` | GRC Dashboard |
| \`/llll review\` | Human Expert Escalation |
| \`/llll guard push\` | Pre-push compliance gate |
| \`/llll guard release\` | Pre-release artifact scan |
| \`/llll override [ID] [justification]\` | Override SOFT_BLOCK |

Additional data (read when the mode requires it):
- Scan patterns: \`${INSTALL_DIR}/scan-patterns.md\`
- Guard patterns: \`${INSTALL_DIR}/guard-patterns.md\`

---

## Guard Reminder

When the user mentions pushing, deploying, publishing, or releasing:
→ Suggest \`/llll guard push\` before \`git push\`
→ Suggest \`/llll guard release\` before \`npm publish\`

---

## Registration Detection

Check \`~/.layrix/config.json\` for \`"registered": true\`:
- Present → LLLL Basic (full output, no folding)
- Absent/false → LLLL Unregistered (fold Medium/Low findings, show registration hint)

---

## Mandatory Output Rules

1. Every output begins with: \`Output Mode: LLLL Unregistered\` or \`Output Mode: LLLL Basic\`
2. Every output ends with: Education Insight → Disclaimer → Next steps menu
3. Disclaimer (append verbatim):
   \`\`\`
   ---
   ⚠️ Disclaimer:
   This content is generated by AI and may be incomplete or inaccurate.
   Human compliance expert or legal professional review is recommended.
   \`\`\`
4. LLLL never writes files — read-only analysis only.
EOF
)

mkdir -p "$(dirname "$AGENTS_MD")"

if [[ ! -f "$AGENTS_MD" ]]; then
  echo "$LLLL_SECTION" > "$AGENTS_MD"
  echo "✓ Created $AGENTS_MD"
else
  if grep -q 'LLLL — Embedded Compliance Layer' "$AGENTS_MD" 2>/dev/null; then
    echo "LLLL section already present in $AGENTS_MD — skipping."
  else
    echo "" >> "$AGENTS_MD"
    echo "---" >> "$AGENTS_MD"
    echo "" >> "$AGENTS_MD"
    echo "$LLLL_SECTION" >> "$AGENTS_MD"
    echo "✓ Appended LLLL section to $AGENTS_MD"
  fi
fi

echo "  Start a Codex session and type /llll to activate."
