#!/usr/bin/env bash
# LLLL installer for OpenAI Codex CLI
# Usage: ./install-codex.sh [--uninstall]
#
# Creates or updates ~/.codex/AGENTS.md with LLLL integration. The LLLL section sits between
# BEGIN/END markers, so running this again after `git pull` replaces it in place (upgrade) and
# --uninstall removes exactly that section. The file is backed up before any change.

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
AGENTS_MD="$HOME/.codex/AGENTS.md"
BEGIN_MARK="<!-- BEGIN LLLL (managed by install-codex.sh; do not edit between the markers) -->"
END_MARK="<!-- END LLLL -->"
LEGACY_HEAD="# LLLL — Embedded Compliance Layer"
LEGACY_LAST="4. LLLL never writes files — read-only analysis only."

case "${1:-}" in
  ""|--uninstall) ;;
  *) echo "Usage: $0 [--uninstall]" >&2; exit 2 ;;
esac

# The version comes from SKILL.md, the one place it is written.
VERSION="$(sed -n 's/.*Embedded Compliance Layer v\([0-9][0-9.]*\).*/\1/p' "$INSTALL_DIR/SKILL.md" | head -1)"
if [[ -z "$VERSION" ]]; then
  echo "Error: could not read the version from $INSTALL_DIR/SKILL.md." >&2
  exit 1
fi

LLLL_SECTION=$(cat << EOF
# LLLL — Embedded Compliance Layer

You have **LLLL (Layrix Logic Layer Loop) v${VERSION}** active as an embedded compliance engine.

---

## Passive Activation (Design-Time Mode)

After ANY output involving feature planning, PRD generation, architecture design, or code generation with compliance relevance, append:

\`\`\`
## ⚖️ Layrix Compliance Layer

Triggered domains:
- [domain — reason]

Potential issues:
- [gaps]

What is missing:
- [evidence or policy gaps]

What to do next:
| Action | Owner |
|--------|-------|

Preventive design suggestions:
- [specific change]

Education insight:
- Compliance: [concept]
- Business: [implication]

Next:
[1] Continue  [2] /llll deep  [3] /llll checklist  [4] /llll brief  [5] /llll diff
\`\`\`

---

## Command Invocation

When the user types any \`/llll\` command:

1. Read \`${INSTALL_DIR}/SKILL.md\` — the core LLLL operating spec. It names reference files (listed below) to read for specific modes.
2. Read \`${INSTALL_DIR}/compliance-checklist-master.md\` — the compliance domain framework.
3. Execute the requested mode exactly as specified in SKILL.md.

Supported commands:

| Command | Mode |
|---------|------|
| \`/llll\` | Diagnosis |
| \`/llll deep\` | Deep Analysis |
| \`/llll checklist\` | Structured Intake |
| \`/llll brief\` | Expert Handoff Brief |
| \`/llll diff\` | Feature vs Policy Coverage |
| \`/llll scan\` | Automated Security Scan |
| \`/llll fix [ID]\` | Fix scan finding |
| \`/llll grc\` | GRC Dashboard |
| \`/llll review\` | Human Expert Escalation |
| \`/llll guard push\` | Pre-push compliance gate |
| \`/llll guard release\` | Pre-release artifact scan |
| \`/llll override [ID] [justification]\` | Override SOFT_BLOCK |

Additional data (read when the mode requires it):
- Scan patterns: \`${INSTALL_DIR}/scan-patterns.md\`
- Guard patterns: \`${INSTALL_DIR}/guard-patterns.md\`
- Reference files that SKILL.md names (read the one a mode needs, in full, from \`${INSTALL_DIR}/\`): \`mode-scan.md\`, \`mode-guard-review.md\`, \`menus.md\`, \`output-standards.md\`, \`observation-storage.md\`

---

## Guard Reminder

When the user mentions pushing, deploying, publishing, or releasing:
→ Suggest \`/llll guard push\` before \`git push\`
→ Suggest \`/llll guard release\` before \`npm publish\`

---

## Registration Detection

Check \`~/.layrix/config.json\` for \`"registered": true\`:
- Present → LLLL Basic (full output, no folding)
- Absent/false → LLLL Unregistered (half-visibility: in every finding table show round(N/2) of N rows, highest severity first, list the folded ones by name, show registration hint)

---

## Mandatory Output Rules

1. Every output begins with: \`Output Mode: LLLL Unregistered\` or \`Output Mode: LLLL Basic\`
2. Every output ends with: Education Insight → Disclaimer → Next steps menu
3. Disclaimer (append verbatim):
   \`\`\`
   ---
   ⚠️ Disclaimer:
   This content is generated by AI and may be incomplete or inaccurate.
   Human compliance expert or legal professional review is recommended.
   \`\`\`
4. LLLL never writes files — read-only analysis only.
EOF
)

# Prints stdin without any LLLL section: the marked one, or the unmarked one that older versions
# of this installer appended. Exits 3 if a section starts and never ends, so nothing is cut blindly.
strip_llll() {
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" -v lh="$LEGACY_HEAD" -v ll="$LEGACY_LAST" '
    state == 0 && $0 == b  { state = 1; next }
    state == 1             { if ($0 == e) state = 0; next }
    state == 0 && $0 == lh { state = 2; next }
    state == 2             { if ($0 == ll) state = 0; next }
    { print }
    END { if (state != 0) exit 3 }'
}

has_section() {
  grep -qxF -e "$BEGIN_MARK" -e "$LEGACY_HEAD" "$1"
}

mkdir -p "$(dirname "$AGENTS_MD")"

if [[ ! -f "$AGENTS_MD" ]]; then
  if [[ "${1:-}" == "--uninstall" ]]; then
    echo "Nothing to remove: $AGENTS_MD does not exist."
    exit 0
  fi
  printf '%s\n%s\n%s\n' "$BEGIN_MARK" "$LLLL_SECTION" "$END_MARK" > "$AGENTS_MD"
  echo "✓ Created $AGENTS_MD (LLLL v${VERSION})"
  echo "  Start a Codex session and type /llll to activate."
  exit 0
fi

if [[ "${1:-}" == "--uninstall" ]] && ! has_section "$AGENTS_MD"; then
  echo "No LLLL section in $AGENTS_MD. Nothing to remove."
  exit 0
fi

BACKUP="${AGENTS_MD}.bak.$(date +%s)"
cp "$AGENTS_MD" "$BACKUP"

TMP="$(mktemp "${AGENTS_MD}.XXXXXX")"
STRIPPED="$(mktemp "${AGENTS_MD}.XXXXXX")"
if ! strip_llll < "$AGENTS_MD" > "$STRIPPED"; then
  rm -f "$TMP" "$STRIPPED"
  echo "Error: an LLLL section in $AGENTS_MD starts but its end was not found." >&2
  echo "       $AGENTS_MD is unchanged. Remove the section by hand, then run this again." >&2
  exit 1
fi
# Drop the blank lines left at the end where the section was, so running again does not add more.
awk '/^[[:space:]]*$/ { blanks++; next } { while (blanks > 0) { print ""; blanks-- } print }' "$STRIPPED" > "$TMP"
rm -f "$STRIPPED"

if [[ "${1:-}" == "--uninstall" ]]; then
  cat "$TMP" > "$AGENTS_MD" && rm -f "$TMP"
  echo "✓ Removed the LLLL section from $AGENTS_MD (backup: $BACKUP)"
  exit 0
fi

# Keep what was there, then add the current section; a blank line separates them if there is content.
if grep -q '[^[:space:]]' "$TMP"; then
  printf '\n' >> "$TMP"
fi
printf '%s\n%s\n%s\n' "$BEGIN_MARK" "$LLLL_SECTION" "$END_MARK" >> "$TMP"
cat "$TMP" > "$AGENTS_MD" && rm -f "$TMP"

echo "✓ Installed LLLL v${VERSION} section in $AGENTS_MD (backup: $BACKUP)"
echo "  Start a Codex session and type /llll to activate."
